name: Deploy Blazor WebAssembly to GitHub Pages

on:
  push:
    branches:
      - master  # Replace with your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x  # Adjust to your .NET version

      - name: Publish Blazor WebAssembly app
        run: dotnet publish code/App/OMKR.Services.ContentBlog.WebApp -c Release -o output

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output/wwwroot
